"""Add contact_number_2 field

Revision ID: 551923cb6539
Revises: feeddb00e0f9
Create Date: 2023-08-17 08:19:13.468744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551923cb6539'
down_revision = 'feeddb00e0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number_2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('contact_number_2')

    # ### end Alembic commands ###
