"""Add image paths 4, 5, and 6

Revision ID: 7d70954aa8d4
Revises: 8c8c5fe3bef7
Create Date: 2023-08-16 08:47:24.094629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d70954aa8d4'
down_revision = '8c8c5fe3bef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path_4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_path_5', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('image_path_5')
        batch_op.drop_column('image_path_4')

    # ### end Alembic commands ###
