"""Add website_url column

Revision ID: 825ecd92e938
Revises: b3ea6410ed04
Create Date: 2023-08-13 23:42:26.504333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825ecd92e938'
down_revision = 'b3ea6410ed04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
