"""Add image_path_2 and image_path_3 columns

Revision ID: 8c8c5fe3bef7
Revises: 825ecd92e938
Create Date: 2023-08-16 01:06:44.437228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8c5fe3bef7'
down_revision = '825ecd92e938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_path_3', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('image_path_3')
        batch_op.drop_column('image_path_2')

    # ### end Alembic commands ###
