"""Add contact_number field

Revision ID: feeddb00e0f9
Revises: 7d70954aa8d4
Create Date: 2023-08-17 07:23:29.967538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feeddb00e0f9'
down_revision = '7d70954aa8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
